import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,Bell,CalendarDays,Check,ChevronRight,Clock3,Download,Filter,HeartPulse,LayoutDashboard,Menu,Moon,PanelLeftClose,PanelLeftOpen,Search,Settings,ShieldCheck,Sparkles,Sun,Users,Wifi,X,Zap} from "lucide-react";
import {Area,AreaChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {activities,alerts as seedAlerts,contributions,ecgBase,patients,riskVectors,telemetrySeries} from "./data";
import type {AlertItem,Patient} from "./types";
type View="dashboard"|"patients"|"telemetry"|"risk"|"alerts";
const nav=[["dashboard","Overview",LayoutDashboard],["patients","Patients",Users],["telemetry","Live Telemetry",Activity],["risk","Risk Assessment",ShieldCheck],["alerts","Alerts & Triage",Bell]] as const;
const cls=(s:string)=>s.toLowerCase();
export default function App(){
 const [view,setView]=useState<View>("dashboard"),[selected,setSelected]=useState(patients[0]),[collapsed,setCollapsed]=useState(false),[dark,setDark]=useState(false),[alerts,setAlerts]=useState<AlertItem[]>(seedAlerts),[search,setSearch]=useState(""),[toast,setToast]=useState("");
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2800);return()=>clearTimeout(t)},[toast]);
 const openPatient=(p:Patient)=>{setSelected(p);setView("telemetry")};
 const ack=(id:string)=>{setAlerts(a=>a.map(x=>x.id===id?{...x,acknowledged:true}:x));setToast("Alert acknowledged.")};
 return <div className="shell">
  <aside className={"sidebar "+(collapsed?"collapsed":"")}>
   <div className="brand"><div className="brandmark"><HeartPulse size={20}/></div>{!collapsed&&<div><b>SYS<span>.LIVE</span></b><small>Clinical Intelligence</small></div>}</div>
   <label>WORKSPACE</label>{nav.map(([id,name,Icon])=><button className={"nav "+(view===id?"active":"")} onClick={()=>setView(id)} key={id}><Icon size={18}/>{!collapsed&&<span>{name}</span>}{id==="alerts"&&!collapsed&&alerts.some(a=>!a.acknowledged)&&<i>{alerts.filter(a=>!a.acknowledged).length}</i>}</button>)}
   <div className="sidefill"/>{!collapsed&&<div className="engine"><div><Sparkles size={14}/> MEEN Engine <em/></div><b>Inference online</b><small>Calibrated risk model · v1.0</small></div>}
   <button className="nav"><Settings size={18}/>{!collapsed&&<span>Settings</span>}</button><button className="nav" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>} {!collapsed&&<span>Collapse sidebar</span>}</button>
   {!collapsed&&<div className="doctor"><div>KR</div><span><b>Dr. Kavita Rao</b><small>Attending physician</small></span></div>}
  </aside>
  <main className="main">
   <header><div className="headtitle"><button className="mobile" onClick={()=>setCollapsed(!collapsed)}><Menu size={19}/></button><div><small>CCU / CLINICAL OPERATIONS</small><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div></div><div className="headactions"><span className="system"><i/> All systems operational</span><button onClick={()=>setView("alerts")}><Bell size={17}/>{alerts.some(a=>!a.acknowledged)&&<i/>}</button><button onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><div className="user">KR <span>Dr. Kavita Rao<small>Attending</small></span></div></div></header>
   <div className="content">
    {view==="dashboard"&&<Dashboard go={setView} open={openPatient} alerts={alerts}/>}
    {view==="patients"&&<Patients search={search} setSearch={setSearch} open={openPatient}/>}
    {view==="telemetry"&&<Telemetry patient={selected}/>}
    {view==="risk"&&<Risk patient={selected}/>}
    {view==="alerts"&&<Alerts alerts={alerts} ack={ack} open={(id)=>{const p=patients.find(x=>x.id===id);if(p)openPatient(p)}}/>}
   </div>
  </main>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
function Dashboard({go,open,alerts}:{go:(v:View)=>void;open:(p:Patient)=>void;alerts:AlertItem[]}){const high=patients.filter(p=>p.riskLevel==="High"||p.riskLevel==="Critical").length;return <><div className="intro"><div><span className="eyebrow">LIVE CLINICAL FEED</span><h2>Good morning, Dr. Rao</h2><p>Current patient risk and telemetry picture across your care units.</p></div><div className="date"><CalendarDays size={15}/> Monday, 21 September 2026</div></div>
 <div className="metrics"><Metric icon={<Users/>} label="Patients monitored" value="5" sub="2 actively streaming" tone="teal"/><Metric icon={<ShieldCheck/>} label="High-risk patients" value={String(high)} sub="Requires clinical review" tone="amber"/><Metric icon={<Activity/>} label="Telemetry uptime" value="99.8%" sub="Connected devices" tone="blue"/><Metric icon={<Bell/>} label="Open alerts" value={String(alerts.filter(a=>!a.acknowledged).length)} sub="Unacknowledged events" tone="red"/></div>
 <div className="grid"><Card title="Priority patients" sub="Patients requiring the closest attention" action={<button onClick={()=>go("patients")}>View all <ChevronRight size={13}/></button>}><div className="table head"><span>Patient</span><span>Vitals</span><span>Risk</span><span>Status</span></div>{patients.slice(0,4).map(p=><button className="row" key={p.id} onClick={()=>open(p)}><PatientName p={p}/><span className="vitals"><b>♥ {p.heartRate}</b> SpO₂ {p.spo2}%</span><Risk level={p.riskLevel} score={p.riskScore}/><Status s={p.status}/></button>)}</Card>
 <Card title="Live telemetry" sub="Selected patient · A-7742" action={<button onClick={()=>go("telemetry")}>Open <ChevronRight size={13}/></button>}><div className="bigvital"><span>Heart rate</span><b>88 <small>BPM</small></b><em>● Stable</em></div><div className="chart"><ResponsiveContainer><AreaChart data={telemetrySeries}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#18a295" stopOpacity=".3"/><stop offset="1" stopColor="#18a295" stopOpacity="0"/></linearGradient></defs><Area dataKey="hr" type="monotone" stroke="#12998d" fill="url(#g)" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></div><div className="mini"><Mini n="BP" v="145/90" u="mmHg" s="Elevated"/><Mini n="SpO₂" v="96" u="%" s="Normal"/><Mini n="Temp" v="37.2" u="°C" s="Normal"/></div></Card></div>
 <div className="grid lower"><Card title="Risk vectors" sub="MEEN multi-disease assessment" action={<button onClick={()=>go("risk")}>Assessment <ChevronRight size={13}/></button>}><div className="risks">{riskVectors.map(r=><RiskBar key={r.name} {...r}/>)}</div></Card><Card title="Clinical activity" sub="Most recent system events"><div className="activity">{activities.map((a,i)=><div key={i}><span className={"activityIcon "+a.type}>{a.type==="alert"?<AlertTriangle/>:a.type==="telemetry"?<Activity/>:<ShieldCheck/>}</span><div><b>{a.title}</b><small>{a.detail}</small></div><time>{a.time}</time></div>)}</div></Card></div></>}
function Patients({search,setSearch,open}:{search:string;setSearch:(s:string)=>void;open:(p:Patient)=>void}){const list=useMemo(()=>patients.filter(p=>[p.name,p.id,p.room,...p.conditions].join(" ").toLowerCase().includes(search.toLowerCase())),[search]);return <><div className="intro"><div><span className="eyebrow">PATIENT REGISTRY</span><h2>Patient management</h2><p>Monitor status, vitals and risk signals from one workspace.</p></div><button className="primary">+ Add patient</button></div><Card title="All patients" sub="Demo clinical registry"><div className="toolbar"><div className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, ID, room or condition..."/></div><button><Filter size={15}/> Filters</button><button><Download size={15}/> Export</button></div><div className="fulltable"><div className="table head"><span>Patient</span><span>Room</span><span>Vitals</span><span>Risk</span><span>Conditions</span><span>Status</span></div>{list.map(p=><button className="row" key={p.id} onClick={()=>open(p)}><PatientName p={p}/><span>{p.room} · {p.bed}</span><span className="vitals">{p.heartRate} BPM · {p.spo2}%</span><Risk level={p.riskLevel} score={p.riskScore}/><span className="conditions">{p.conditions.map(c=><i key={c}>{c}</i>)}</span><Status s={p.status}/></button>)}</div></Card></>}
function Telemetry({patient}:{patient:Patient}){const [hr,setHr]=useState(patient.heartRate);useEffect(()=>{const t=setInterval(()=>setHr(x=>Math.max(65,Math.min(115,x+(Math.random()>.5?1:-1)))),2200);return()=>clearInterval(t)},[]);const ecg=ecgBase.map((v,i)=>({i,value:v+Math.sin(i*2)*1.5}));return <><div className="intro"><div><span className="eyebrow">LIVE PATIENT MONITOR</span><h2>{patient.name}</h2><p>{patient.id} · {patient.room} / {patient.bed} · {patient.age} years · {patient.gender}</p></div><span className="live">● DEVICE CONNECTED</span></div><div className="metrics"><Vital label="Heart rate" value={String(hr)} unit="BPM"/><Vital label="Blood pressure" value={patient.systolic+"/"+patient.diastolic} unit="mmHg" warn/><Vital label="Oxygen saturation" value={String(patient.spo2)} unit="%"/><Vital label="Temperature" value={patient.temperature.toFixed(1)} unit="°C"/></div><div className="grid"><Card title="ECG waveform" sub="Lead II · simulated live telemetry"><div className="ecg"><ResponsiveContainer><LineChart data={ecg}><Line dataKey="value" stroke="#16a394" strokeWidth={2} dot={false}/><YAxis domain={[20,90]} hide/><XAxis dataKey="i" hide/></LineChart></ResponsiveContainer></div><div className="ecgfoot">25 mm/s <span/> 10 mm/mV <span/> Lead II <b>Signal quality 98%</b></div></Card><Card title="Telemetry trends" sub="Recent physiological trend"><div className="trendchart"><ResponsiveContainer><LineChart data={telemetrySeries}><CartesianGrid stroke="var(--line)" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="time" tick={{fontSize:9,fill:"var(--muted)"}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:9,fill:"var(--muted)"}} tickLine={false} axisLine={false}/><Tooltip/><Line dataKey="hr" stroke="#159b90" strokeWidth={2} dot={false}/><Line dataKey="systolic" stroke="#c98b2b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Card></div></>}
function Risk({patient}:{patient:Patient}){return <><div className="intro"><div><span className="eyebrow">MEEN RISK ENGINE</span><h2>Explainable risk assessment</h2><p>Calibrated patient-level prediction with feature-level explanations.</p></div><span className="live">● MEEN v1.0 · ONLINE</span></div><div className="riskhero"><div className="ring"><b>{patient.riskScore}</b><small>/ 100</small><span>Overall risk</span></div><div><Risk level={patient.riskLevel}/><h3>{patient.riskLevel} multi-disease risk detected</h3><p>The demo model combines clinical history and current telemetry. Review the feature contributions before a clinical decision.</p><div className="tags"><span>✓ Calibration active</span><span>◷ Updated 8 min ago</span><span>✦ XAI available</span></div></div></div><div className="grid lower"><Card title="Disease risk vectors" sub="Probability estimates by condition"><div className="risks">{riskVectors.map(r=><RiskBar key={r.name} {...r}/>)}</div></Card><Card title="Model diagnostics" sub="Current inference session"><div className="diagnostics">{[["Model","MEEN Ensemble"],["Base learners","CatBoost + XGBoost"],["Meta learner","Calibrated Deep MLP"],["Calibration","Platt + Isotonic"],["Signal filter","Kalman + EWMA"],["Inference latency","84 ms"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></Card></div><Card title="Why this prediction?" sub="SHAP-style feature contribution for selected patient"><div className="xai"><div>{contributions.map(c=><div className="contribution" key={c.feature}><div><span>{c.feature}</span><b className={c.direction}>{c.label}</b></div><i><em className={c.direction} style={{width:(c.value*2)+"%"}}/></i></div>)}</div><div className="explain"><Sparkles size={18}/><h3>Local explanation</h3><small>LIME-style patient reasoning</small><p>For <b>{patient.name}</b>, current risk is most influenced by elevated blood pressure, glycemic burden and cardiovascular biomarkers. SpO₂ contributes a lower-risk signal.</p><div>✓ Explanation is tied to the current patient state.</div></div></div></Card></>}
function Alerts({alerts,ack,open}:{alerts:AlertItem[];ack:(id:string)=>void;open:(id:string)=>void}){return <><div className="intro"><div><span className="eyebrow">CLINICAL SAFETY QUEUE</span><h2>Alerts & triage</h2><p>Review telemetry events and acknowledge completed actions.</p></div><button>Clinical protocol</button></div><div className="alertstats"><b>{alerts.filter(a=>!a.acknowledged).length}<small>Open alerts</small></b><b>{alerts.filter(a=>a.acknowledged).length}<small>Acknowledged</small></b><b>1.8 min<small>Avg. response</small></b></div><Card title="Alert queue" sub="Prioritized by clinical severity"><div className="alertlist">{alerts.map(a=><div className={"alert "+(a.acknowledged?"done":"")} key={a.id}><div className={"alerticon "+cls(a.severity)}>{a.severity==="Critical"?<Zap/>:<AlertTriangle/>}</div><div><b>{a.title}</b><span className={"severity "+cls(a.severity)}>{a.severity}</span><p>{a.description}</p><small>{a.patientName} · {a.patientId} · {a.time}</small></div><div className="alertactions"><button onClick={()=>open(a.patientId)}>Open patient</button>{!a.acknowledged?<button className="primary" onClick={()=>ack(a.id)}><Check size={14}/> Acknowledge</button>:<span>✓ Acknowledged</span>}</div></div>)}</div></Card></>}
function Card({title,sub,action,children}:{title:string;sub:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="card"><div className="cardhead"><div><h3>{title}</h3><p>{sub}</p></div>{action}</div>{children}</section>}
function Metric({icon,label,value,sub,tone}:{icon:React.ReactNode;label:string;value:string;sub:string;tone:string}){return <div className="metric"><div className={"metricicon "+tone}>{icon}</div><div><span>{label}</span><b>{value}</b><small>{sub}</small></div></div>}
function Vital({label,value,unit,warn=false}:{label:string;value:string;unit:string;warn?:boolean}){return <div className="metric"><div className={"metricicon "+(warn?"amber":"teal")}><HeartPulse size={18}/></div><div><span>{label}</span><b>{value}<small> {unit}</small></b><small className={warn?"warn":""}>{warn?"Elevated":"Normal"}</small></div></div>}
function Mini({n,v,u,s}:{n:string;v:string;u:string;s:string}){return <div><span>{n}</span><b>{v}<small>{u}</small></b><em>{s}</em></div>}
function PatientName({p}:{p:Patient}){return <span className="patient"><i>{p.name.split(" ").map(x=>x[0]).join("")}</i><b>{p.name}<small>{p.id} · {p.age}y · {p.gender}</small></b></span>}
function Risk({level,score}:{level:Patient["riskLevel"];score?:number}){return <span className={"risk "+cls(level)}>● {level}{score!==undefined&&<b>{score}</b>}</span>}
function Status({s}:{s:Patient["status"]}){return <span className={"status "+cls(s)}>● {s}</span>}
function RiskBar(r:{name:string;score:number;level:Patient["riskLevel"];trend:string}){return <div className="riskbar"><div><span>{r.name}</span><b>{r.score}%</b></div><i><em className={cls(r.level)} style={{width:r.score+"%"}}/></i><small><Risk level={r.level}/> <span>{r.trend==="up"?"↑ Increasing":r.trend==="down"?"↓ Improving":"→ Stable"}</span></small></div>}
