import type {ActivityItem,AlertItem,FeatureContribution,Patient,RiskVector} from "./types";
export const patients:Patient[]=[
{id:"A-7742",name:"Arjun Mehta",age:54,gender:"Male",room:"ICU-04",bed:"B-02",status:"Monitoring",heartRate:88,systolic:145,diastolic:90,spo2:96,temperature:37.2,riskScore:82,riskLevel:"High",conditions:["Hypertension","Type 2 Diabetes"],admission:"18 Sep 2026",doctor:"Dr. Kavita Rao"},
{id:"B-1028",name:"Priya Sharma",age:42,gender:"Female",room:"Ward-07",bed:"B-11",status:"Stable",heartRate:76,systolic:124,diastolic:80,spo2:98,temperature:36.8,riskScore:34,riskLevel:"Moderate",conditions:["Diabetes"],admission:"19 Sep 2026",doctor:"Dr. Sameer Khan"},
{id:"C-3119",name:"Rahul Verma",age:67,gender:"Male",room:"ICU-02",bed:"B-01",status:"Review",heartRate:103,systolic:158,diastolic:94,spo2:92,temperature:37.7,riskScore:91,riskLevel:"Critical",conditions:["Cardiovascular","Hypertension"],admission:"20 Sep 2026",doctor:"Dr. Kavita Rao"},
{id:"D-4581",name:"Neha Kapoor",age:36,gender:"Female",room:"Ward-03",bed:"B-05",status:"Stable",heartRate:71,systolic:118,diastolic:76,spo2:99,temperature:36.6,riskScore:18,riskLevel:"Low",conditions:["None recorded"],admission:"20 Sep 2026",doctor:"Dr. Sameer Khan"},
{id:"E-9204",name:"Vikram Singh",age:59,gender:"Male",room:"CCU-01",bed:"B-03",status:"Monitoring",heartRate:95,systolic:151,diastolic:88,spo2:94,temperature:37.1,riskScore:73,riskLevel:"High",conditions:["Cardiovascular","Diabetes"],admission:"17 Sep 2026",doctor:"Dr. Kavita Rao"}];
export const riskVectors:RiskVector[]=[
{name:"Hypertension",score:84,level:"High",trend:"up"},{name:"Type 2 Diabetes",score:71,level:"High",trend:"stable"},{name:"Cardiovascular",score:63,level:"Moderate",trend:"up"},{name:"Respiratory",score:18,level:"Low",trend:"down"}];
export const contributions:FeatureContribution[]=[
{feature:"HbA1c",value:42,label:"+0.42",direction:"positive"},{feature:"Troponin",value:38,label:"+0.38",direction:"positive"},{feature:"LDL",value:29,label:"+0.29",direction:"positive"},{feature:"Resting BP",value:25,label:"+0.25",direction:"positive"},{feature:"BMI",value:18,label:"+0.18",direction:"positive"},{feature:"SpO₂",value:9,label:"-0.09",direction:"negative"}];
export const alerts:AlertItem[]=[
{id:"ALT-204",patientId:"C-3119",patientName:"Rahul Verma",title:"Critical oxygen saturation",description:"SpO₂ dropped below the configured monitoring threshold.",severity:"Critical",time:"2 min ago",acknowledged:false},
{id:"ALT-198",patientId:"A-7742",patientName:"Arjun Mehta",title:"Elevated multi-disease risk",description:"MEEN risk engine detected increasing cardiovascular and hypertension risk.",severity:"Warning",time:"8 min ago",acknowledged:false},
{id:"ALT-193",patientId:"E-9204",patientName:"Vikram Singh",title:"Blood pressure trend rising",description:"Systolic pressure has increased across the last telemetry window.",severity:"Warning",time:"17 min ago",acknowledged:true},
{id:"ALT-187",patientId:"B-1028",patientName:"Priya Sharma",title:"Telemetry connection restored",description:"Patient device resumed streaming after a brief interruption.",severity:"Info",time:"32 min ago",acknowledged:true}];
export const activities:ActivityItem[]=[
{title:"Risk assessment completed",detail:"A-7742 · Multi-disease screening",time:"8 min ago",type:"prediction"},{title:"Telemetry threshold crossed",detail:"C-3119 · SpO₂ 92%",time:"12 min ago",type:"alert"},{title:"Live telemetry received",detail:"5 patients online",time:"18 min ago",type:"telemetry"},{title:"Clinical note added",detail:"A-7742 · Dr. Kavita Rao",time:"26 min ago",type:"note"},{title:"Risk model refreshed",detail:"MEEN v1.0 · calibration check",time:"41 min ago",type:"prediction"}];
export const ecgBase=[52,49,51,50,48,52,51,50,49,53,52,50,51,49,52,50,48,51,50,52,51,49,50,51,48,54,72,34,78,51,49,52,50,51,49,53,50,51,48,52,50,51,49,52,50,51,48,52];
export const telemetrySeries=Array.from({length:24},(_,i)=>({time:`${String(10+Math.floor(i/4)).padStart(2,"0")}:${String((i%4)*15).padStart(2,"0")}`,hr:82+Math.round(Math.sin(i/3)*5)+(i%5===0?2:0),spo2:96+Math.round(Math.cos(i/4)),systolic:138+Math.round(Math.sin(i/5)*8),diastolic:86+Math.round(Math.cos(i/4)*4)}));
